version: '3'

networks:
  shared:
    name: shared_dev_planning_knock_out_whist

services:
  backend:
    image: mcr.microsoft.com/devcontainers/rust:1-1-bullseye
    volumes:
      - ../../..:/workspaces:cached
    networks:
      - shared
    command: sleep infinity