name: Build and Publish
on:
  push: 
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      # Allow running workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
      
      - name: Build the frontend
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push the deployment docker container
        id: push
        uses: docker/build-push-action@v6.18.0
        with:
         context: .
         file: deployment/dockerfile
         push: true
         tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Digital Ocean
        uses: digitalocean/app_action/deploy@v2
        env:
          SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
        with:
          token: ${{ secrets.YOUR_DIGITALOCEAN_ACCESS_TOKEN_VARIABLE_NAME }}


